### ISSUE TITLE
Wrong Paths being generated for API

### ISSUE THREAD

**Issue by robbydooo** [stormpath/stormpath-laravel-auth-driver#6]
Hi there,

I have tried implementing this today but there are far too many bugs currently.

The wrong URLs are being generated in StormpathUserProvider, it should be this

$this->client->get($identifier, \Stormpath\Stormpath::ACCOUNT);

not 

$this->client->get('accounts/'. $identifier, \Stormpath\Stormpath::ACCOUNT);

Currently the paths generated are creating "accounts/https://api.stormpath.com" which breaks the code completely.

same in retrieveByToken and updateRememberToken

Also the User Object that gets returned does not work as intended. 
Calling any of the magic functions result in an error. E.g.

Auth::user()->getFullName()

Call to undefined method Stormpath\StormpathUser::getFullName()

although Auth::user()->fullname does work.

Its possible I have misunderstodo the intention although not have user details on the user object would be pretty clunky.

**Comment by bretterer** [comment]
@robbydooo Version 0.1.0-alpha.3 should fix the issue with the $identifier.

as for the getFullName(), that is not a method that is available for `Auth::user()`

The available methods can be received by running 

```
dump(get_class_methods(Auth::user()));
```

this will output 

```
0 => "__construct"
  1 => "getAuthIdentifier"
  2 => "getAuthPassword"
  3 => "getRememberToken"
  4 => "setRememberToken"
  5 => "getRememberTokenName"
  6 => "__get"
  7 => "__set"
  8 => "__isset"
  9 => "__unset"
```

The fullName is not a method that is accessable via the User object returned from Laravel authentication but is returned by the Stormpath User Object.

If you have any other questions, please let me know.

**Comment by robbydooo** [comment]
Awesome thanks will try it out!
